#!/bin/bash

echo "---------BUILD HUGO------------"
hugo -b https://cdevframework.io/ --environment prod

echo "------PDOC DOCUMENTATION-------"
#here=$(pwd)
#cd $cdevprojectpath
#. ./scripts/activate
#./scripts/make_documentation
#cd $here

echo "-------UPLOAD TO STAGE-----------"

aws s3 cp ./public s3://cdevframework.io --recursive
